name: just_do_it
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  share_plus: ^4.0.0
  open_file: ^3.2.1
  auto_size_text: ^3.0.0
  dash_chat_2: ^0.0.15
  flutter_overlay_loader: ^2.0.0
  cached_network_image: ^3.2.3
  cupertino_rounded_corners: ^2.1.1
  pinput: ^2.2.31
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  path_provider: ^2.0.2
  url_launcher: ^6.1.10
  webview_flutter: ^3.0.4
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.20
  sliding_up_panel: ^2.0.0+1
  permission_handler: ^10.1.0
  scale_button: ^2.1.2
  intl: ^0.17.0
  flutter_secure_storage: ^6.0.0
  flutter_smart_dialog: ^4.5.3+2
  flutter_vector_icons: ^1.0.0
  keyboard_actions: ^4.0.1
  lottie: ^2.0.0
  image_picker: ^0.8.5+3
  file_picker: ^4.0.0
  fluttertoast: ^8.0.9
  web_socket_channel: ^2.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^12.0.4
  firebase_dynamic_links: ^5.1.1
  skeleton_loader: ^2.0.0+4
  firebase_analytics: ^10.2.1
  share_plus: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    # - family: SFBold
    #   fonts:
    #     - asset: assets/fonts/SFPDisplay-Black.ttf  

